import { PUBLICATION } from "./Entities";

export const GET_ALL_BY_USER = `GET_ALL_BY_USER==>${PUBLICATION}`;
export const LOADING = `LOADING_REQUEST==>${PUBLICATION}`;
export const LOADING_COMMENTS = `LOADING_COMMENTS==>${PUBLICATION}`;
export const ERROR = `ERROR_REQUEST==>${PUBLICATION}`;
export const DEFAULT = `DEFAULT==>${PUBLICATION}`;
